In [ ]:
import numpy as np
import pandas as pd

import statsmodels.api as sm
from sklearn.linear_model import LinearRegression

from matplotlib import pyplot as plt
import seaborn as sns
sns.set_theme()

In [ ]:
df = pd.read_csv('/content/ecommerce_newest_1.csv')

<ipython-input-2-ff7be7b1f932>:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/ecommerce_newest_1.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99668 entries, 0 to 99667
Data columns (total 30 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   id                                   99668 non-null  int64
 1   full_name                            99668 non-null  object
 2   gender                               99668 non-null  object
 3   state                                99668 non-null  object
 4   postal_code                          99668 non-null  object
 5   city                                 99668 non-null  object
 6   country                              99668 non-null  object
 7   age                                  99668 non-null  int64
 8   order_id                             99668 non-null  int64
 9   product_name                         99668 non-null  object
 10  product_id                           99668 non-null  int64
 11  brand                                99668 non-null  object
 12  num_of_item                          99668 non-null  int64
 13  cost                                 99668 non-null  float64
 14  sale_price                           99668 non-null  float64
 15  retail_price                         99668 non-null  float64
 16  product_category                     99668 non-null  object
 17  created_at                           99668 non-null  object
 18  status                               99668 non-null  object
 19  year                                 99668 non-null  int64
 20  revenue                              99668 non-null  float64
 21  age_group                            99668 non-null  object
 22  profit_margin                        99668 non-null  float64
 23  cost_increase_10                     99668 non-null  float64
 24  new_profit_margin_cost_increase_10   99668 non-null  float64
 25  cost_decrease_10                     99668 non-null  float64
 26  new_profit_margin_cost_decrease_10   99668 non-null  float64
 27  selling_price_increase_10            99668 non-null  float64
 28  new_revenue_price_increase_10        99668 non-null  float64
 29  new_profit_margin_price_increase_10  99668 non-null  float64
dtypes: float64(12), int64(6), object(12)
memory usage: 22.8+ MB

calculate the total revenue for all product per year

In [ ]:
total_revenue_per_year = df.groupby('year')['revenue'].sum()
total_revenue_per_year

year
2019    1.795033e+05
2020    5.877470e+05
2021    1.155441e+06
2022    1.884165e+06
2023    3.084833e+06
2024    4.339711e+06
Name: revenue, dtype: float64

In [ ]:
df['cost*num_of_item'] = df['cost'] * df['num_of_item']

In [ ]:
df['sale_price*num_of_item'] = df['sale_price'] * df['num_of_item']

calculate total cost for all product per year

In [ ]:
total_cost_per_year = df.groupby('year')['cost*num_of_item'].sum()
total_cost_per_year

year
2019    8.664994e+04
2020    2.826574e+05
2021    5.545331e+05
2022    9.038919e+05
2023    1.488246e+06
2024    2.085480e+06
Name: cost*num_of_item, dtype: float64

calculate total profit margin per year

In [ ]:
total_profit_margin_per_year = ((total_revenue_per_year - total_cost_per_year) / total_revenue_per_year) * 100
total_profit_margin_per_year

year
2019    51.727950
2020    51.908319
2021    52.006809
2022    52.026924
2023    51.756038
2024    51.944256
dtype: float64

In [ ]:
cost_increase_10 = total_cost_per_year * 1.1
new_profit_margin_10 = ((total_revenue_per_year - cost_increase_10) / total_revenue_per_year) * 100
new_profit_margin_10

year
2019    46.900745
2020    47.099151
2021    47.207490
2022    47.229616
2023    46.931642
2024    47.138682
dtype: float64

In [ ]:
cost_decrease_10 = total_cost_per_year * 0.9
new_profit_margin_decrease_10 = ((total_revenue_per_year - cost_decrease_10) / total_revenue_per_year) * 100
new_profit_margin_decrease_10

year
2019    56.555155
2020    56.717487
2021    56.806128
2022    56.824231
2023    56.580434
2024    56.749831
dtype: float64

In [ ]:
price_increase_10 = total_revenue_per_year * 1.1
new_profit_margin_price_increase_10 = ((price_increase_10 - total_cost_per_year) / price_increase_10) * 100
new_profit_margin_price_increase_10

year
2019    56.116318
2020    56.280290
2021    56.369827
2022    56.388112
2023    56.141853
2024    56.312960
dtype: float64

In [ ]:
df2 = pd.DataFrame({'year' : [2019, 2020, 2021, 2022, 2023, 2024],
                    'total_revenue_per_year ' : [1.795033e+05,	5.877470e+05, 1.155441e+06, 1.884165e+06, 3.084833e+06, 4.339711e+06],
                    'total_cost_per_year' : [8.664994e+04, 2.826574e+05, 5.545331e+05, 9.038919e+05, 1.488246e+06, 2.085480e+06],
                    'total_profit_margin_per_year' : [51.727950, 51.908319, 52.006809, 52.026924, 51.756038, 51.944256],
                    'new_profit_margin_cost_increase_10' : [46.900745, 47.099151, 47.207490, 47.229616, 46.931642, 47.138682],
                    'new_profit_margin_cost_decrease_10' : [56.555155, 56.717487, 56.806128, 56.824231, 56.580434, 56.749831],
                    'new_profit_margin_price_increase_10' : [56.116318, 56.280290, 56.369827, 56.388112, 56.141853, 56.312960]
                    })

In [ ]:
df2

,year,total_revenue_per_year,total_cost_per_year,total_profit_margin_per_year,new_profit_margin_cost_increase_10,new_profit_margin_cost_decrease_10,new_profit_margin_price_increase_10
0,2019,179503.3,86649.94,51.727950,46.900745,56.555155,56.116318
1,2020,587747.0,282657.40,51.908319,47.099151,56.717487,56.280290
2,2021,1155441.0,554533.10,52.006809,47.207490,56.806128,56.369827
3,2022,1884165.0,903891.90,52.026924,47.229616,56.824231,56.388112
4,2023,3084833.0,1488246.00,51.756038,46.931642,56.580434,56.141853
5,2024,4339711.0,2085480.00,51.944256,47.138682,56.749831,56.312960

In [ ]:
df2.to_csv('ecommerce_newest_2.csv', index=False)